### ISSUE TITLE
Push Ruby Tutorial to Personal Github

### ISSUE THREAD

**Issue by Bjornkjohnson** [WhiteWhaleXYZ/WhiteWhale#10]
Bjorn- Done
Andrew - Done
Tony - Done
Yarley - Done
Nick - Done

**Comment by andrewjbaumann** [comment]
Edit made on 2/19@3:43pm

**Comment by Bjornkjohnson** [comment]
Edit made on 2/20@4:36pm

**Comment by n-critser** [comment]
Edit made on 2/21@11pm
Did everyone do the toyapp or just hello world?

**Comment by andrewjbaumann** [comment]
I did the toy app as well

**Comment by Bjornkjohnson** [comment]
Just hello world, but I'm gonna work on more.
