### ISSUE TITLE
Add git tutorial links to readme file

### ISSUE THREAD

**Issue by Bjornkjohnson** [WhiteWhaleXYZ/WhiteWhale#12]

**Comment by n-critser** [comment]
Links Below for working with Git.  Branching and merging need to be solid. Also, need to be solid about
flow of code from Dev --->Test ---> Prod , to keep clean code only in Production. 

[add ssh key](https://help.github.com/articles/changing-a-remote-s-url/)
[git branching](http://www.git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)
[markdown guide for wiki](https://guides.github.com/features/mastering-markdown/)
[emoji:whale:](http://www.emoji-cheat-sheet.com/)
