### ISSUE TITLE
Finish Ruby Tutorial by Sunday 2/22 8PM 

### ISSUE THREAD

**Issue by Bjornkjohnson** [WhiteWhaleXYZ/WhiteWhale#9]
Bjorn- Not Done
Andrew - Not Done
Tony - Not Done
Yarley - Not Done
Nick - Not Done

**Comment by Bjornkjohnson** [comment]
Bjorn- Not Done
Andrew - Not Done
Tony - Update existing tutorial to use bootstrap
Yarley - Not Done
Nick - Not Done

**Comment by andrewjbaumann** [comment]
Everyone did it, checked
